version: '3'
services:
  app:
    image: node:12-alpine
    working_dir: /home/node/app
    environment:
      - ENV=DEV
      - SERVER_PORT=3000
      - LOGGER_LEVEL=debug
      - LOGGER_LOG_HTTP_REQUESTS=true
      - EMAIL_PROVIDER_1_ID=sendgrid
      - EMAIL_PROVIDER_1_TOKEN=
      - EMAIL_PROVIDER_2_ID=postmark
      - EMAIL_PROVIDER_2_TOKEN=
    volumes:
      - .:/home/node/app
    ports:
      - '3000:3000'
    command: 'npm start'

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=http://localhost:3000/api-docs
    ports:
      - '9999:8080'
